config/routes.rb
Rundown::Application.routes.draw do
  get "pages/home"
  root to: 'pages#home'

  resources :items, except: [:edit]
  resources :users, except: [:edit, :new]

  resource  :sessions, only: [:create, :destroy]
  match '/signout' => 'sessions#destroy', as: :sign_out
  match "/auth/:provider/callback" => "sessions#create"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
end

app/models/item.rb
class Item
  include Mongoid::Document
  field :name, type: String
  field :price, type: Float
  field :quantity, type: Integer
  field :notes, type: String

  embeds_one :public
  accepts_nested_attributes_for :public

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: {
    only_integer: true, greater_than_or_equal_to: 0
  }

  private
    def price_to_float(price_str)
      begin
        price = (Float( price_str.strip.gsub(/\$|\,/,'') )).round(2)
      rescue Exception => e
        price_int = ''
      end
    end

    def initialize(attrs={}, opts=nil)
      attrs[:quantity] ||= 1
      attrs[:price] = price_to_float(attrs[:price])
      super(attrs, opts)
      self.public or self.build_public
      self
    end
end

class Public
  include Mongoid::Document
  field :title
  field :body

  embedded_in :item
end

app/models/user.rb
class User
  include Mongoid::Document

  field :provider, type: String
  field :uid, type: String
  field :name, type: String
  field :email, type: String

  validates :provider, presence: true
  validates :uid, presence: true, uniqueness: {scope: :provider}
  validates :name, presence: true
  validate :whitelist_email

  def whitelist_email
    unless User::Email.where(email: email).exists?
      errors.add :email, 'must be whitelisted for an account by an administrator.'
    end
  end

  class Email
    include Mongoid::Document

    field :email, type: String

    validates :email, presence: true, uniqueness: {case_sensitive: false}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
    redirect_to '/auth/google_oauth2' unless current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate, except: :show
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if current_user
      flash[:error] = "You're already logged in."
      redirect_to '/'
      return
    end

    auth = request.env['omniauth.auth']
    if user = User.where(provider: auth['provider'], uid: auth['uid']).first
      session[:user_id] = user._id
      flash[:notice] = 'logged in as ' + auth['info']['name']
      redirect_to '/'
    else
      redirect_to controller: :users, action: :create, user: {
        provider: auth['provider'],
        uid:      auth['uid'],
        name:     auth['info']['name'],
        email:    auth['info']['email'],
      }
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are logged out."
    redirect_to '/'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, except: :create

  def index
    @users = User.all
  end

  def show
  end

  def create
    user = User.new params[:user]

    respond_to do |format|
      if user.save
        format.html { redirect_to '/', notice: 'New user account created' }
      else
        format.html do
          flash[:error] = 'Could not create a new account'
          redirect_to '/'
        end
      end
    end
  end

  def update
    current_user.update_attributes(
      name:  params[:user][:name],
      email: params[:user][:email],
    )

    respond_to do |format|
      format.html { render :show }
    end
  end

  def destroy
    current_user.destroy
    redirect_to '/', notice: 'User account deleted'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_price(price)
    sprintf '%0.2f', price
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :quantity
    = f.number_field :quantity
  = f.fields_for :public, @item.public do |f_pub|
    %h3 Public Information
    .field
      = f_pub.label :title
      %br
      = f_pub.text_field :title
    .field
      = f_pub.label :body
      %br
      = f_pub.text_area :body
  .actions
    = f.submit 'Save'

app/views/items/index.html.haml
%h1 Listing items

%table
  %tr
    %th Name
    %th Price
    %th Quantity
    %th
    %th

  - @items.each do |item|
    %tr
      %td= item.name
      %td= show_price item.price
      %td= item.quantity
      %td= link_to 'Show', item
      %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
- if current_user
  %h1 Editing item
  = render 'form'
  = link_to 'Back', items_path
- else
  %h1= @item.public.title
  #public_body= @item.public.body

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rundown</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.haml
- if current_user
  Show stuff.
- else
  = link_to 'Sign in for administative access', '/auth/google_oauth2'

app/views/users/index.html.haml
%h1 Administrative Users

%table
  %tr
    %th Name
    %th Email
    %th
  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      - if user == current_user
        %td= link_to 'edit name/email', user

app/views/users/show.html.haml
= form_for current_user do |f|
  - if current_user.errors.any?
    #error_explanation
      %h2= "#{pluralize(current_user.errors.count, "error")}:"
      %ul
        - current_user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
= link_to 'Back to all users', users_path